#! /usr/bin/env python

import sys

fname = sys.argv[1]

n_lines = 0
bits = [0] * 32

with open(fname) as f:
    for line in f:
        try:
            val = int(line,16)
            n_lines += 1
            for i in range(32):
                if val & (1 << i):
                    bits[i] += 1.0
        except:
            pass

freqs = [ b/n_lines for b in bits ]
sys.stderr.write(str(freqs))
print('min:{min} max:{max}'.format(min=min(freqs), max=max(freqs)))


